### ISSUE TITLE
二维码过期

### ISSUE THREAD

**Issue by TopGuo** [stulzq/Alipay.Demo.PCPayment#1]
您好，我在根据你的blog进行操作的后时候，在测试支付那块，当我扫码的时候，收到二维码过期！

**Comment by stulzq** [comment]
你好，请问你是否时使用的是支付宝沙箱环境。使用沙箱环境是需要专属的沙箱账号来进行支付，如果需要app扫码是，需要专属的沙箱支付宝app，不然就会出现你说的这种情况。沙箱账号和app在沙箱后台可以查看

**Comment by TopGuo** [comment]
嗯嗯，是沙箱环境！好吧，晓得了
谢谢！！！
